Repository CarbonLilly/LillyStation12, pull requests merged in 2019-12, with the labels that each got.

#1 Engineering Update
  maps/derp/flare.dmm
Labels: enhancement

#6 Felinids
  code/__defines/mobs.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/external/standard.dm
  code/modules/species/species.dm
  code/modules/species/station/station.dm
  code/modules/sprite_accessories/_accessory_hair.dm
  icons/effects/species.dmi
  icons/mob/human_races/species/human/body.dmi
Labels: Coding, enhancement

#10 Vacant Room Fix
  maps/torch/torch3_deck3.dmm
  maps/torch/torch6_bridge.dmm
Labels: Mapping, enhancement
